<?php 
header("Content-type: text/css");
$primar=$_POST["primar"];
require_once(cv.html);
?>
@import url('https://themes.googleusercontent.com/fonts/css?kit=Yeh3y7ciGQhij8XzUSI-wN9BwJ9QSusUFFTiN987YIbvi2WQbTlLajdXq3UgoDiw');
            ol{
                margin:0;padding:0
            }
            table td,table th{padding:0}
            .c16{
                border-right-style:solid;
                padding:0pt 18pt 14.4pt 18pt;
                border-bottom-color:<?=$primar?>;
                border-top-width:1.5pt;
                border-right-width:1.5pt;
                border-left-color:<?=$primar?>;
                vertical-align:top;
                border-right-color:<?=$primar?>;
                border-left-width:0pt;
                border-top-style:solid;
                background-color:<?=$primar?>;
                border-left-style:solid;
                border-bottom-width:1.5pt;
                width:193.5pt;
                border-top-color:<?=$primar?>;
                border-bottom-style:solid}.c2{border-right-style:solid;
                padding:0pt 18pt 14.4pt 18pt;
                border-bottom-color:<?=$primar?>;
                border-top-width:1.5pt;
                border-right-width:1.5pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:<?=$primar?>;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:1.5pt;
                width:193.5pt;
                border-top-color:<?=$primar?>;
                border-bottom-style:solid}.c12{border-right-style:solid;
                padding:14.4pt 3.6pt 0pt 3.6pt;
                border-bottom-color:#000000;
                border-top-width:0pt;
                border-right-width:0pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:0pt;
                width:77.3pt;
                border-top-color:#000000;
                border-bottom-style:solid
            }
            .c21{
                border-right-style:solid;
                padding:0pt 18pt 14.4pt 18pt;
                border-bottom-color:<?=$primar?>;
                border-top-width:1.5pt;
                border-right-width:0pt;
                border-left-color:<?=$primar?>;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:1.5pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:1.5pt;
                width:272.5pt;
                border-top-color:<?=$primar?>;
                border-bottom-style:solid}.c20{border-right-style:solid;
                padding:0pt 18pt 14.4pt 18pt;
                border-bottom-color:<?=$primar?>;
                border-top-width:0pt;
                border-right-width:0pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:1.5pt;
                width:272.5pt;
                border-top-color:#000000;
                border-bottom-style:solid}.c14{border-right-style:solid;
                padding:0pt 3.6pt 0pt 3.6pt;
                border-bottom-color:#000000;
                border-top-width:0pt;
                border-right-width:0pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:0pt;
                width:77.3pt;
                border-top-color:#000000;
                border-bottom-style:solid
            }
            .c24{
                border-right-style:solid;
                padding:0pt 18pt 14.4pt 18pt;
                border-bottom-color:<?=$primar?>;
                border-top-width:1.5pt;
                border-right-width:0pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:1.5pt;
                width:193.5pt;
                border-top-color:<?=$primar?>;
                border-bottom-style:solid}.c1{border-right-style:solid;
                padding:0pt 3.6pt 14.4pt 3.6pt;
                border-bottom-color:#000000;
                border-top-width:0pt;
                border-right-width:0pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:0pt;
                width:77.3pt;
                border-top-color:#000000;
                border-bottom-style:solid}.c19{border-right-style:solid;
                border-bottom-color:#000000;
                border-top-width:0pt;
                border-right-width:1.5pt;
                border-left-color:#000000;
                vertical-align:top;
                border-right-color:<?=$primar?>;
                border-left-width:0pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:0pt;
                width:272.5pt;
                border-top-color:#000000;
                border-bottom-style:solid
            }
            .c15{
                border-right-style:solid;border-bottom-color:#000000;
                border-top-width:0pt;
                border-right-width:0pt;
                border-left-color:<?=$primar?>;
                vertical-align:top;
                border-right-color:#000000;
                border-left-width:1.5pt;
                border-top-style:solid;
                border-left-style:solid;
                border-bottom-width:0pt;
                width:195.5pt;
                border-top-color:#000000;
                border-bottom-style:solid
            }
            .c18{
                color:#636a6b;
                font-weight:400;
                text-decoration:none;
                vertical-align:baseline;
                font-size:11pt;
                font-family:"Century Gothic";
                font-style:normal
            }
            .c7{
                color:#636a6b;
                font-weight:700;
                text-decoration:none;
                vertical-align:baseline;
                font-size:11pt;
                font-family:"Century Gothic";
                font-style:normal
            }
            .c4{
                color:#000000;
                font-weight:400;
                text-decoration:none;
                vertical-align:baseline;
                font-size:11pt;
                font-family:"Arial";
                font-style:normal
            }
            .c3{
                color:#636a6b;
                font-weight:400;
                text-decoration:none;
                vertical-align:baseline;
                font-size:14pt;
                font-family:"Century Gothic";
                font-style:normal
            }
            .c13{
                padding-top:18pt;
                padding-bottom:3pt;
                line-height:1.07;
                page-break-after:avoid;
                text-align:center
            }
            .c0{
                padding-top:0pt;
                padding-bottom:3pt;
                line-height:1.07;
                page-break-after:avoid;
                text-align:center
            }
            .c23{
                padding-top:0pt;
                padding-bottom:18pt;
                line-height:1.0;
                text-align:center
            }
            .c8{
                padding-top:0pt;
                padding-bottom:3pt;
                line-height:1.07;
                text-align:center
            }
            .c22{
                margin-left:1.5pt;
                border-spacing:0;
                border-collapse:collapse;
                margin-right:auto
            }
            .c25{
                padding-top:0pt;padding-bottom:0pt;
                line-height:1.0;
                text-align:left
            }
            .c6{
                border-spacing:0;
                border-collapse:collapse;
                margin-right:auto
            }
            .c11{
                padding-top:0pt;
                padding-bottom:0pt;
                line-height:1.15;
                text-align:left
            }
            .c5{
                padding-top:0pt;
                padding-bottom:0pt;
                line-height:1.0;
                text-align:center
            }
            .c17{
                background-color:#ffffff;
                max-width:468pt;
                padding:72pt 72pt 72pt 72pt
            }
            .c10{height:11pt}
            .c9{height:0pt}
            .title{padding-top:24pt;
                color:#000000;
                font-weight:700;
                font-size:36pt;
                padding-bottom:6pt;
                font-family:"Arial";
                line-height:1.0;
                page-break-after:avoid;
                text-align:left
            }
            .subtitle{
                padding-top:18pt;
                color:#666666;
                font-size:24pt;
                padding-bottom:4pt;
                font-family:"Georgia";
                line-height:1.0;
                page-break-after:avoid;
                font-style:italic;
                text-align:left
            }
            li{
                color:#000000;
                font-size:11pt;
                font-family:"Arial"
            }
            p{
                margin:0;
                color:#000000;
                font-size:11pt;
                font-family:"Arial"
            }
            h1{
                padding-top:18pt;
                color:#636a6b;
                font-size:14pt;
                padding-bottom:3pt;
                font-family:"Century Gothic";
                line-height:1.07;
                text-align:center
            }
            h2{
                padding-top:0pt;
                color:#636a6b;
                font-weight:700;
                font-size:11pt;
                padding-bottom:3pt;
                font-family:"Century Gothic";
                line-height:1.07;
                text-align:center
                }
            h3{
                padding-top:2pt;
                color:#806000;
                font-size:11pt;
                padding-bottom:0pt;
                font-family:"Century Gothic";
                line-height:1.07;
                text-align:center
            }
            h4{
                padding-top:2pt;
                color:#806000;
                font-size:11pt;
                padding-bottom:0pt;
                font-family:"Century Gothic";
                line-height:1.07;
                font-style:italic;
                text-align:center
            }
            h5{
                padding-top:2pt;
                color:#806000;
                font-weight:700;
                font-size:11pt;
                padding-bottom:0pt;
                font-family:"Century Gothic";
                line-height:1.07;
                text-align:center
            }
            h6{
                padding-top:2pt;
                color:#806000;
                font-weight:700;
                font-size:11pt;
                padding-bottom:0pt;
                font-family:"Century Gothic";
                line-height:1.07;
                font-style:italic;
                text-align:center
            }
